---
- name: install netscaler ingress
  hosts: all
  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"

  tasks:
    - name: install virtualenv
      become: true
      ansible.builtin.package:
        name: "{{ virtualenv_pkg_name[ansible_distribution] }}"
        state: present
      vars:
        virtualenv_pkg_name:
          CentOS: python-virtualenv
          Ubuntu: python3-virtualenv

    - name: Install multi python packages with version specifiers
      ansible.builtin.pip:
        virtualenv: "{{ ansible_env.PWD }}/k8s-python"
        virtualenv_python: python3
        name:
          - kubernetes
          - jsonpatch

    - name: Create a k8s namespace
      vars:
        ansible_python_interpreter: "{{ ansible_env.PWD }}/k8s-python/bin/python"

      kubernetes.core.k8s:
        name: citrix-ingress-controller
        api_version: v1
        kind: Namespace
        state: present

    - name: Create SECRET
      vars:
        ansible_python_interpreter: "{{ ansible_env.PWD }}/k8s-python/bin/python"
      kubernetes.core.k8s:
        state: present
        definition: 
          apiVersion: v1
          kind: Secret
          type: Opaque
          metadata:
            name: "nslogin"
            namespace: "citrix-ingress-controller"
          data:
            username: "{{ citrix_cic.username | b64encode }}"
            password: "{{ citrix_cic.password | b64encode }}"

    - name: Download Helm
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: ~/get_helm.sh
        mode: '700'

    - name: install Helm
      shell: ./get_helm.sh
      register: ret
      changed_when: "'is already latest' not in ret.stdout"

    - name: "Install Helm Diff"
      kubernetes.core.helm_plugin:
        plugin_path: "https://github.com/databus23/helm-diff"
        state: present

    - name: Add citrix chart repo
      kubernetes.core.helm_repository:
        name: citrix
        repo_url: "https://citrix.github.io/citrix-helm-charts/"

    - name: Deploy chart
      kubernetes.core.helm:
        # release_state: absent
        kubeconfig: "{{ kubeconfig_path }}"
        namespace: "citrix-ingress-controller"
        name: cic
        chart_ref: citrix/citrix-ingress-controller 
        values: "{{ citrix_ingress_controller_values }}"
